#!/bin/sh
# Starts the Fluss datalake tiering service as a standalone Flink job. This
# job continuously reads Fluss's internal changelog/log and commits it into
# Iceberg tables in the Polaris catalog, using the credentials Polaris
# generated for the fluss_tiering principal (polaris/bootstrap.sh).
#
# Run from inside the flink-jobmanager container:
#   docker compose exec flink-jobmanager /opt/flink-cdc-pipelines/run-tiering-service.sh
set -e

FLUSS_VERSION="${FLUSS_VERSION:-0.9.1-incubating}"

# FLUSS_CLIENT_ID/SECRET are generated by polaris/bootstrap.sh at bootstrap
# time and not known when the image is built, so source them here rather
# than baking them into the image or docker-compose.yml.
if [ -f /polaris/creds.env ]; then
  set -a
  . /polaris/creds.env
  set +a
fi

# Optional instance number (default 1). Tiering jobs are stateless and
# coordinated by the Fluss coordinator's FIFO table queue, so running N of
# them divides per-table tiering lag roughly by N. With the medallion's 14
# tables, one job round-robins to ~6 min worst-case Iceberg lag; two jobs
# halve that. -d: return once submitted, so the Makefile can start several.
INSTANCE="${1:-1}"

exec /opt/flink/bin/flink run -d \
  -Dpipeline.name="Fluss Iceberg Tiering Service #${INSTANCE}" \
  /opt/flink/opt/fluss-flink-tiering-${FLUSS_VERSION}.jar \
  --fluss.bootstrap.servers fluss-coordinator:9123 \
  --datalake.format iceberg \
  --datalake.iceberg.type rest \
  --datalake.iceberg.uri http://polaris:8181/api/catalog \
  --datalake.iceberg.warehouse lakehouse \
  --datalake.iceberg.oauth2-server-uri http://polaris:8181/api/catalog/v1/oauth/tokens \
  --datalake.iceberg.credential "${FLUSS_CLIENT_ID}:${FLUSS_CLIENT_SECRET}" \
  --datalake.iceberg.scope PRINCIPAL_ROLE:ALL \
  --datalake.iceberg.header.X-Iceberg-Access-Delegation vended-credentials \
  --datalake.iceberg.s3.endpoint http://seaweedfs:8333 \
  --datalake.iceberg.s3.path-style-access true \
  --datalake.iceberg.s3.region us-east-1 \
  --datalake.iceberg.io-impl org.apache.iceberg.aws.s3.S3FileIO
